# Generated by Django 5.2.5 on 2025-09-02 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
        ("empresas", "0001_initial"),
        ("nucleos", "0001_initial"),
        ("organizacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="nucleo",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nucleos.nucleo"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="organizacao",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizacoes.organizacao"),
        ),
        migrations.AddField(
            model_name="briefingevento",
            name="evento",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="agenda.evento"),
        ),
        migrations.AddField(
            model_name="eventolog",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="agenda.evento"
            ),
        ),
        migrations.AddField(
            model_name="eventolog",
            name="usuario",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="feedbacknota",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="feedbacks", to="agenda.evento"
            ),
        ),
        migrations.AddField(
            model_name="feedbacknota",
            name="usuario",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="historicalfeedbacknota",
            name="evento",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="agenda.evento",
            ),
        ),
        migrations.AddField(
            model_name="historicalfeedbacknota",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalfeedbacknota",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inscricaoevento",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="inscricoes", to="agenda.evento"
            ),
        ),
        migrations.AddField(
            model_name="inscricaoevento",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="inscricoes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="materialdivulgacaoevento",
            name="avaliado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materiais_avaliados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materialdivulgacaoevento",
            name="evento",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="agenda.evento"),
        ),
        migrations.AddField(
            model_name="parceriaevento",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="parcerias", to="empresas.empresa"
            ),
        ),
        migrations.AddField(
            model_name="parceriaevento",
            name="evento",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="agenda.evento"),
        ),
        migrations.AddField(
            model_name="parceriaevento",
            name="nucleo",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nucleos.nucleo"
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="nucleo",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nucleos.nucleo"
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="organizacao",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizacoes.organizacao"),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="tarefas_criadas", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tarefalog",
            name="tarefa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="agenda.tarefa"
            ),
        ),
        migrations.AddField(
            model_name="tarefalog",
            name="usuario",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedbacknota",
            unique_together={("usuario", "evento")},
        ),
        migrations.AlterUniqueTogether(
            name="inscricaoevento",
            unique_together={("user", "evento")},
        ),
    ]
