# Generated by Django 5.2.5 on 2025-09-02 18:53

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConviteNucleo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "papel",
                    models.CharField(choices=[("membro", "Membro"), ("coordenador", "Coordenador")], max_length=20),
                ),
                ("limite_uso_diario", models.PositiveSmallIntegerField(default=1)),
                ("data_expiracao", models.DateTimeField(blank=True, null=True)),
                ("usado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Convite para Núcleo",
                "verbose_name_plural": "Convites para Núcleos",
            },
        ),
        migrations.CreateModel(
            name="CoordenadorSuplente",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("periodo_inicio", models.DateTimeField(db_index=True)),
                ("periodo_fim", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "Coordenador Suplente",
                "verbose_name_plural": "Coordenadores Suplentes",
            },
        ),
        migrations.CreateModel(
            name="Nucleo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nome", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="nucleos/avatars/")),
                ("cover", models.ImageField(blank=True, null=True, upload_to="nucleos/capas/")),
                ("ativo", models.BooleanField(default=True)),
                ("mensalidade", models.DecimalField(decimal_places=2, default=Decimal("30.00"), max_digits=8)),
            ],
            options={
                "verbose_name": "Núcleo",
                "verbose_name_plural": "Núcleos",
            },
        ),
        migrations.CreateModel(
            name="ParticipacaoNucleo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "papel",
                    models.CharField(
                        choices=[("membro", "Membro"), ("coordenador", "Coordenador")], default="membro", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("ativo", "Ativo"), ("inativo", "Inativo")],
                        db_index=True,
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("status_suspensao", models.BooleanField(default=False)),
                ("data_suspensao", models.DateTimeField(blank=True, null=True)),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                ("data_decisao", models.DateTimeField(blank=True, null=True)),
                ("justificativa", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Participação no Núcleo",
                "verbose_name_plural": "Participações nos Núcleos",
            },
        ),
    ]
