# Generated by Django 5.2.5 on 2025-09-02 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nucleos", "0001_initial"),
        ("organizacoes", "0001_initial"),
        ("tokens", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="convitenucleo",
            name="token_obj",
            field=models.ForeignKey(
                blank=True,
                db_column="token_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="convites_nucleo",
                to="tokens.tokenacesso",
            ),
        ),
        migrations.AddField(
            model_name="coordenadorsuplente",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="suplencias", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="nucleo",
            name="organizacao",
            field=models.ForeignKey(
                db_column="organizacao",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nucleos",
                to="organizacoes.organizacao",
            ),
        ),
        migrations.AddField(
            model_name="coordenadorsuplente",
            name="nucleo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="coordenadores_suplentes", to="nucleos.nucleo"
            ),
        ),
        migrations.AddField(
            model_name="convitenucleo",
            name="nucleo",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="nucleos.nucleo"),
        ),
        migrations.AddField(
            model_name="participacaonucleo",
            name="decidido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decisoes_participacao",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participacaonucleo",
            name="nucleo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="participacoes", to="nucleos.nucleo"
            ),
        ),
        migrations.AddField(
            model_name="participacaonucleo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="participacoes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="nucleo",
            constraint=models.UniqueConstraint(fields=("organizacao", "slug"), name="uniq_org_slug"),
        ),
        migrations.AlterUniqueTogether(
            name="participacaonucleo",
            unique_together={("user", "nucleo")},
        ),
    ]
