openapi: 3.0.3
info:
  title: Hubx API
  version: 1.0.0
paths:
  /me/:
    get:
      summary: Ver perfil do usuário
      operationId: getPerfil
      responses:
        "200":
          description: Perfil retornado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: Atualizar perfil do usuário
      operationId: putPerfil
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "200":
          description: Perfil atualizado

  /me/password/:
    put:
      su
