# Generated by Django 5.2.5 on 2025-09-02 18:53

import core.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaAssociado",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("saldo", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12)),
            ],
            options={
                "verbose_name": "Conta do Associado",
                "verbose_name_plural": "Contas dos Associados",
                "ordering": ["user"],
            },
        ),
        migrations.CreateModel(
            name="FinanceiroLog",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("importar", "Importar Pagamentos"),
                            ("criar_cobranca", "Criar Cobrança"),
                            ("distribuir_receita", "Distribuir Receita"),
                            ("ajuste_lancamento", "Ajuste de Lançamento"),
                            ("repasse", "Repasse de Receita"),
                            ("editar_centro", "Editar Centro de Custo"),
                            ("editar_lancamento", "Editar Lançamento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dados_anteriores", models.JSONField(blank=True, default=dict)),
                ("dados_novos", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Log Financeiro",
                "verbose_name_plural": "Logs Financeiros",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinanceiroTaskLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nome_tarefa", models.CharField(max_length=255)),
                ("executada_em", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=20)),
                ("detalhes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Log de Tarefa Financeira",
                "verbose_name_plural": "Logs de Tarefas Financeiras",
                "ordering": ["-executada_em"],
            },
        ),
        migrations.CreateModel(
            name="ImportacaoPagamentos",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("arquivo", models.CharField(max_length=255)),
                ("data_importacao", models.DateTimeField(default=django.utils.timezone.now)),
                ("total_processado", models.PositiveIntegerField(default=0)),
                ("erros", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("processando", "Em processamento"), ("concluido", "Concluído"), ("erro", "Erro")],
                        default="processando",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Importação de Pagamentos",
                "verbose_name_plural": "Importações de Pagamentos",
                "ordering": ["-data_importacao"],
            },
        ),
        migrations.CreateModel(
            name="IntegracaoConfig",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("erp", "ERP"),
                            ("contabilidade", "Contabilidade"),
                            ("gateway", "Gateway de Pagamento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_url", core.fields.URLField(max_length=255)),
                ("credenciais_encrypted", core.fields.EncryptedCharField(blank=True, max_length=512)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Configuração de Integração",
                "verbose_name_plural": "Configurações de Integração",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="IntegracaoIdempotency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("provedor", models.CharField(max_length=100)),
                ("recurso", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Idempotência de Integração",
                "verbose_name_plural": "Idempotências de Integração",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegracaoLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provedor", models.CharField(max_length=100)),
                ("acao", models.CharField(max_length=100)),
                ("payload_in", models.JSONField(blank=True, default=dict)),
                ("payload_out", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(max_length=50)),
                ("duracao_ms", models.PositiveIntegerField(default=0)),
                ("erro", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log de Integração",
                "verbose_name_plural": "Logs de Integração",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LancamentoFinanceiro",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mensalidade_associacao", "Mensalidade Associação"),
                            ("mensalidade_nucleo", "Mensalidade Núcleo"),
                            ("ingresso_evento", "Ingresso Evento"),
                            ("aporte_interno", "Aporte Interno"),
                            ("aporte_externo", "Aporte Externo"),
                            ("despesa", "Despesa"),
                            ("ajuste", "Ajuste"),
                        ],
                        max_length=32,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_lancamento", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "data_vencimento",
                    models.DateTimeField(blank=True, help_text="Data limite para pagamento do lançamento", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("pago", "Pago"), ("cancelado", "Cancelado")],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("ultima_notificacao", models.DateTimeField(blank=True, null=True)),
                ("ajustado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Lançamento Financeiro",
                "verbose_name_plural": "Lançamentos Financeiros",
                "ordering": ["-data_lancamento"],
            },
        ),
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("organizacao", "Organização"), ("nucleo", "Núcleo"), ("evento", "Evento")],
                        max_length=12,
                    ),
                ),
                ("saldo", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12)),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="centros_custo",
                        to="agenda.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
                "ordering": ["nome"],
            },
        ),
    ]
