# Generated by Django 5.2.5 on 2025-09-02 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financeiro", "0001_initial"),
        ("nucleos", "0001_initial"),
        ("organizacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="centrocusto",
            name="nucleo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="centros_custo",
                to="nucleos.nucleo",
            ),
        ),
        migrations.AddField(
            model_name="centrocusto",
            name="organizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="centros_custo",
                to="organizacoes.organizacao",
            ),
        ),
        migrations.AddField(
            model_name="contaassociado",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contas_financeiras",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="financeirolog",
            name="usuario",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="financeirotasklog",
            index=models.Index(fields=["nome_tarefa", "executada_em"], name="idx_task_nome_exec"),
        ),
        migrations.AddField(
            model_name="importacaopagamentos",
            name="usuario",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="centro_custo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="lancamentos", to="financeiro.centrocusto"
            ),
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="conta_associado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lancamentos",
                to="financeiro.contaassociado",
            ),
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="lancamento_original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ajustes",
                to="financeiro.lancamentofinanceiro",
            ),
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="originador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aportes_lancados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Aporte",
            fields=[],
            options={
                "verbose_name": "Aporte",
                "verbose_name_plural": "Aportes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("financeiro.lancamentofinanceiro",),
        ),
        migrations.AddIndex(
            model_name="importacaopagamentos",
            index=models.Index(fields=["data_importacao"], name="idx_importacao_data"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["centro_custo", "conta_associado"], name="idx_centro_conta"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["centro_custo"], name="idx_lanc_centro"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["conta_associado"], name="idx_lanc_conta"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["data_lancamento"], name="idx_lanc_dt_lanc"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["data_vencimento"], name="idx_lanc_dt_venc"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["status"], name="idx_lanc_status"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(
                fields=["centro_custo", "conta_associado", "tipo", "valor", "data_lancamento"],
                name="idx_lanc_duplicidade",
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(
                fields=["centro_custo", "conta_associado", "status", "data_vencimento"], name="idx_lanc_cc_status_venc"
            ),
        ),
    ]
