# Generated by Django 5.2.5 on 2025-09-02 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feed", "0001_initial"),
        ("nucleos", "0001_initial"),
        ("organizacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="nucleo",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nucleos.nucleo"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="organizacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="posts", to="organizacoes.organizacao"
            ),
        ),
        migrations.AddField(
            model_name="moderacaopost",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="moderacao", to="feed.post"
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="feed.post"),
        ),
        migrations.AddField(
            model_name="flag",
            name="post",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="flags", to="feed.post"),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="feed.post"
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="bookmarks", to="feed.post"
            ),
        ),
        migrations.AddField(
            model_name="postview",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="visualizacoes", to="feed.post"
            ),
        ),
        migrations.AddField(
            model_name="postview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="visualizacoes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="reacao",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reacoes", to="feed.post"
            ),
        ),
        migrations.AddField(
            model_name="reacao",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reacoes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="posts", to="feed.tag"),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("post", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="flag",
            unique_together={("post", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("user", "post")},
        ),
        migrations.AlterUniqueTogether(
            name="reacao",
            unique_together={("post", "user", "vote")},
        ),
    ]
