name: Codex Setup

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - '.editorconfig'
  workflow_dispatch:

# Evita gastar runner à toa em pushes em sequência
concurrency:
  group: codex-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      PYTHONUNBUFFERED: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      DJANGO_SETTINGS_MODULE: "config.settings"  # ajuste se necessário

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python (com cache do pip)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Mostrar versões
        run: |
          python -V
          pip -V

      - name: Aquecer instalador (evita erros de wheels/compilação)
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Instalar dependências (runtime)
        run: |
          pip install -r requirements.txt

      - name: Sanity check do Django (sem tocar DB)
        run: |
          python -c "import os, django; os.environ.setdefault('DJANGO_SETTINGS_MODULE', os.getenv('DJANGO_SETTINGS_MODULE')); django.setup(); print('✅ Django import OK')"
          python manage.py check --deploy --fail-level WARNING || true

      - name: Resumo de pacotes instalados
        run: |
          pip list --format=columns
